[TAIPY]

[DATA_NODE.initial_data]
storage_type = "csv"
scope = "GLOBAL:SCOPE"
<<<<<<< HEAD
path = "data/modified_supermarkt_sales_plus.csv"

[DATA_NODE.holiday]
storage_type = "csv"
=======
path = "data/supermarkt_sales_plus.csv"

[DATA_NODE.holiday]
default_data = "False:bool"
>>>>>>> 30fd282 (proposition de changement)

[DATA_NODE.level]
default_data = "1:int"

[DATA_NODE.date]

[DATA_NODE.final_data]

[DATA_NODE.model_arima]

<<<<<<< HEAD
[DATA_NODE.model_xgboost]

[DATA_NODE.predictions_arima]

[DATA_NODE.predictions_xgboost]
=======
[DATA_NODE.model_linear_regression]

[DATA_NODE.predictions_arima]

[DATA_NODE.predictions_linear_regression]
>>>>>>> 30fd282 (proposition de changement)

[DATA_NODE.result]

[TASK.task_preprocess_data]
function = "algorithms.algorithms.preprocess:function"
inputs = [ "initial_data:SECTION", "holiday:SECTION", "level:SECTION",]
outputs = [ "final_data:SECTION", "date:SECTION",]
skippable = "False:bool"

[TASK.task_train]
function = "algorithms.algorithms.train_arima:function"
inputs = [ "final_data:SECTION",]
outputs = [ "model_arima:SECTION",]
skippable = "False:bool"

[TASK.task_forecast]
function = "algorithms.algorithms.forecast:function"
inputs = [ "model_arima:SECTION",]
outputs = [ "predictions_arima:SECTION",]
skippable = "False:bool"

<<<<<<< HEAD
[TASK.task_train_xgboost]
function = "algorithms.algorithms.train_xgboost:function"
inputs = [ "final_data:SECTION",]
outputs = [ "model_xgboost:SECTION",]
skippable = "False:bool"

[TASK.task_forecast_xgboost]
function = "algorithms.algorithms.forecast_xgboost:function"
inputs = [ "model_xgboost:SECTION", "date:SECTION",]
outputs = [ "predictions_xgboost:SECTION",]
=======
[TASK.task_train_linear_regression]
function = "algorithms.algorithms.train_linear_regression:function"
inputs = [ "final_data:SECTION",]
outputs = [ "model_linear_regression:SECTION",]
skippable = "False:bool"

[TASK.task_forecast_linear_regression]
function = "algorithms.algorithms.forecast_linear_regression:function"
inputs = [ "model_linear_regression:SECTION", "date:SECTION",]
outputs = [ "predictions_linear_regression:SECTION",]
>>>>>>> 30fd282 (proposition de changement)
skippable = "False:bool"

[TASK.task_result]
function = "algorithms.algorithms.concat:function"
<<<<<<< HEAD
inputs = [ "final_data:SECTION", "predictions_arima:SECTION", "predictions_xgboost:SECTION",]
=======
inputs = [ "final_data:SECTION", "predictions_arima:SECTION", "predictions_linear_regression:SECTION",]
>>>>>>> 30fd282 (proposition de changement)
outputs = [ "result:SECTION",]
skippable = "False:bool"

[SCENARIO.scenario]
<<<<<<< HEAD
tasks = [ "task_preprocess_data:SECTION", "task_train:SECTION", "task_forecast:SECTION", "task_train_xgboost:SECTION", "task_forecast_xgboost:SECTION", "task_result:SECTION",]
=======
tasks = [ "task_preprocess_data:SECTION", "task_train:SECTION", "task_forecast:SECTION", "task_train_linear_regression:SECTION", "task_forecast_linear_regression:SECTION", "task_result:SECTION",]
>>>>>>> 30fd282 (proposition de changement)
additional_data_nodes = []

[SCENARIO.scenario.comparators]

[SCENARIO.scenario.sequences]
